httpd:
  mpm:
    prefork_module:
      StartServers: 10
      MinSpareServers: 10
      MaxSpareServers: 30
      ServerLimit: 1000
      MaxRequestWorkers: 1000
      MaxRequestsPerChild: 5000

    event_module:
      StartServers: 3
      MinSpareThreads: 75
      MaxSpareThreads: 250
      ThreadsPerChild: 25
      MaxRequestWorkers: 400
      MaxConnectionsPerChild: 0

    KeepAlive: "On"
    MaxKeepAliveRequests: 100
    KeepAliveTimeout: 30

